### ISSUE TITLE
Error after node updater

### ISSUE THREAD

**Issue by tmmtta** [Askwrite/node-csgo-reportbot#12]
/root/node_modules/protobufjs/dist/protobuf.js:4688
                            throw Error("failed to import '"+importFilename+"' in '"+filename+"': file not found");
                            ^

Error: failed to import '/root/protos/engine_gcmessages.proto' in '/root/protos/cstrike15_gcmessages.proto': file not found
    at Error (native)
    at ProtoBuf.Builder.BuilderPrototype.import (/root/node_modules/protobufjs/dist/protobuf.js:4688:35)
    at Object.ProtoBuf.loadJson (/root/node_modules/protobufjs/dist/protobuf.js:5183:26)
    at Object.ProtoBuf.loadProto (/root/node_modules/protobufjs/dist/protobuf.js:5086:25)
    at Object.ProtoBuf.loadProtoFile (/root/node_modules/protobufjs/dist/protobuf.js:5132:52)
    at Object.<anonymous> (/root/protos/protos.js:7:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by Askwrite** [comment]
Cant reproduce it, can u give me more info about it?

**Comment by tmmtta** [comment]
nvm use 4.1.1
cd protos
node updater.js
cd ..
node bot
error

**Comment by Askwrite** [comment]
U ran "npm install"? In the main directory?

**Comment by volovik** [comment]
yep, thath true

`root@xubuntuserver:/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot# nodejs bot.js
/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:4688
                            throw Error("failed to import '"+importFilename+"' in '"+filename+"': file not found");
                            ^

Error: failed to import '/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/protos/engine_gcmessages.proto' in '/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/protos/cstrike15_gcmessages.proto': file not found
    at Error (native)
    at ProtoBuf.Builder.BuilderPrototype.import (/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:4688:35)
    at Object.ProtoBuf.loadJson (/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:5183:26)
    at Object.ProtoBuf.loadProto (/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:5086:25)
    at Object.ProtoBuf.loadProtoFile (/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:5132:52)
    at Object.<anonymous> (/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot/protos/protos.js:7:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
root@xubuntuserver:/home/administrator/reportbot/node-csgo-reportbot/node-csgo-reportbot#
`

**Comment by tmmtta** [comment]
npm WARN cannot run in wd csgo-reportbot@1.0.0 npm run update (wd=/root)
https@1.0.0 node_modules/https

process@0.11.5 node_modules/process

q@1.4.1 node_modules/q

readline-sync@1.4.4 node_modules/readline-sync

events@1.1.1 node_modules/events

**Comment by tmmtta** [comment]
also yestarday it was working...

**Comment by Askwrite** [comment]
npm install --unsafe-perm

try so

**Comment by tmmtta** [comment]
it installed, but still... its not working

`root@VPN:~# npm install --unsafe-perm

> csgo-reportbot@1.0.0 install /root
> npm run update


> csgo-reportbot@1.0.0 update /root
> node ./protos/updater.js

base_gcmessages.proto
cstrike15_gcmessages.proto
gcsdk_gcmessages.proto
protos.js
steammessages.proto
updater.js
root@VPN:~# node bot
/root/node_modules/protobufjs/dist/protobuf.js:4688
                            throw Error("failed to import '"+importFilename+"' in '"+filename+"': file not found");
                            ^

Error: failed to import '/root/protos/engine_gcmessages.proto' in '/root/protos/cstrike15_gcmessages.proto': file not found
    at Error (native)
    at ProtoBuf.Builder.BuilderPrototype.import (/root/node_modules/protobufjs/dist/protobuf.js:4688:35)
    at Object.ProtoBuf.loadJson (/root/node_modules/protobufjs/dist/protobuf.js:5183:26)
    at Object.ProtoBuf.loadProto (/root/node_modules/protobufjs/dist/protobuf.js:5086:25)
    at Object.ProtoBuf.loadProtoFile (/root/node_modules/protobufjs/dist/protobuf.js:5132:52)
    at Object.<anonymous> (/root/protos/protos.js:7:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
`

**Comment by tmmtta** [comment]
I found fix. 


```
var fs = require("fs");
var https = require("https");

var baseUrl = "https://raw.githubusercontent.com/SteamDatabase/GameTracking/master/Protobufs/csgo/";
var protos = [
  "base_gcmessages.proto",
  "steammessages.proto",
  "cstrike15_gcmessages.proto",
  "gcsdk_gcmessages.proto",
  "engine_gcmessages.proto"
];

fs.readdir(__dirname, function(err, filenames) {
  if (err) { 
    return err; 
  }

  filenames.forEach(function(filename) {
    console.log(filename);
    if (filename != "protos.js" && filename != "updater.js") {
      fs.unlinkSync(__dirname + "/" + filename);
    }
  });

  protos.forEach(function(proto) {
    var file = fs.createWriteStream(__dirname + "/" + proto);
    https.get(baseUrl + proto, function(response) {
      response.pipe(file);
    });
  });
});

```


delete all from protos/updater.js and paste this code

**Comment by Askwrite** [comment]
Ups, they updated the proto 12hrs ago: http://puu.sh/pR9PL/f077ee403f.png

Thanks ;)
