### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by tmmtta** [Askwrite/node-csgo-reportbot#2]
/root/bot.js:38
        User = new Steam.SteamUser(Client);
               ^
TypeError: undefined is not a function
    at loginAndReport (/root/bot.js:38:16)
    at Object.<anonymous> (/root/bot.js:149:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by Askwrite** [comment]
Hmm, have you installed all the dependencies?

**Comment by M4giiCc** [comment]
How do i install dependecies? Thats where i get lost

**Comment by Askwrite** [comment]
Read the readme pls..
"npm install"
