### ISSUE TITLE
ubuntu, npm start

### ISSUE THREAD

**Issue by debianlulz** [Askwrite/node-csgo-reportbot#22]
root@RareIvory-VM:~/node-csgo-reportbot# node bot.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/node-csgo-reportbot/bot.js:13:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by Askwrite** [comment]
READ THE FUCKING README
