### ISSUE TITLE
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

### ISSUE THREAD

**Issue by Terrix175** [Askwrite/node-csgo-reportbot#23]
I'm Keep Getting This Error.   
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Commandbot\accounts.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (C:\Commandbot\bot.js:17:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

C:\Commandbot>pause
Drücken Sie eine beliebige Taste . . .

**Comment by debianlulz** [comment]
hey man, it looks like possibly you forgot to rename the accounts file to accounts.txt it comes defaulty something like accounts.example.txt
