### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sparkkZ** [Askwrite/node-csgo-reportbot#29]
/root/node_modules/protobufjs/dist/protobuf.js:784
                throw e;
                ^

Error: Parse error at line 1: unexpected '404'
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (/root/node_modules/protobufjs/dist/protobuf.js:779:35)
    at Function.ProtoBuf.DotProto.Parser.parse (/root/node_modules/protobufjs/dist/protobuf.js:797:39)
    at Object.ProtoBuf.loadProto (/root/node_modules/protobufjs/dist/protobuf.js:5086:59)
    at Object.ProtoBuf.loadProtoFile (/root/node_modules/protobufjs/dist/protobuf.js:5132:52)
    at Object.<anonymous> (/root/protos/protos.js:6:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by TheRhanderson** [comment]
**sparkkZ,**

Delete all files from protos folder, keeping only the files **'updater.js'** and **'proto.js'** and try again.

Thanks.

**Comment by TheRhanderson** [comment]
**sparkkZ,**

Check the files ended with _.proto_ and make sure none have this error "**Error: 404 Not Found**"

Thanks.

**Comment by Askwrite** [comment]
updated
