### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by aesto1** [Askwrite/node-csgo-reportbot#3]
what am I doing wrong?
I have installed:node npm install steam

module.js:327
    throw err;
    ^

Error: Cannot find module 'steamid'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Aesto\Desktop\node-csgo-reportbot-master\bot.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by Askwrite** [comment]
Read the readme pls...
