### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Swenlor** [Askwrite/node-csgo-reportbot#38]
![image](https://cloud.githubusercontent.com/assets/25634007/22730813/8d4710a8-ee3c-11e6-904e-f57f7f7873a2.png)

I have read the readme and  the version Node.js i am running is v6.9.5.
npm install
C:\Users\User>node protos/updater.js
module.js:471
    throw err;
    ^
Error: Cannot find module 'C:\Users\User\protos\updater.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by toopski** [comment]
in the cmd promt it says the folder as user/user/protos

yet in the folder pic you have it in downloads and the destination is completely different

**Comment by kotik1998** [comment]
If you getting those akward error, try reinstalling every thing and following the step by step.
