### ISSUE TITLE
Error after 'x  report(s) successfully sent!"

### ISSUE THREAD

**Issue by tmmtta** [Askwrite/node-csgo-reportbot#5]
Everything was ok few times, but now i got error...

/root/node_modules/steam/lib/steam_client.js:114
  this._connection.send(Buffer.concat([header.toBuffer(), body]));
                  ^

TypeError: Cannot read property 'send' of undefined
    at SteamClient._send (/root/node_modules/steam/lib/steam_client.js:114:19)
    at SteamClient.send (/root/node_modules/steam/lib/steam_client.js:123:8)
    at SteamGameCoordinator._send (/root/node_modules/steam/lib/handlers/game_coordinator/index.js:49:16)
    at SteamGameCoordinator.send (/root/node_modules/steam/lib/handlers/game_coordinator/index.js:67:8)
    at null._repeat (/root/bot.js:78:28)
    at wrapper [as _onTimeout] (timers.js:270:19)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by tmmtta** [comment]
nevermind, ran updater again and it works.

**Comment by Askwrite** [comment]
:)
