### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Waller1337** [Askwrite/node-csgo-reportbot#61]
Error: Parse error at line 1: unexpected '404'
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:779:35)
    at Function.ProtoBuf.DotProto.Parser.parse (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:797:39)
    at Object.ProtoBuf.loadProto (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:5128:59)
    at Object.ProtoBuf.loadProtoFile (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:5174:52)
    at Object.<anonymous> (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\protos\protos.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! csgo-reportbot@1.0.0 start: `node bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csgo-reportbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\YOG\AppData\Roaming\npm-cache\_logs\2019-03-11T17_44_42_471Z-debug.log

C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master>

**Comment by verdammnis** [comment]
> Error: Parse error at line 1: unexpected '404'
> at Parser.ProtoBuf.DotProto.ParserPrototype.parse (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:779:35)
> at Function.ProtoBuf.DotProto.Parser.parse (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:797:39)
> at Object.ProtoBuf.loadProto (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:5128:59)
> at Object.ProtoBuf.loadProtoFile (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\node_modules\protobufjs\dist\protobuf.js:5174:52)
> at Object. (C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master\protos\protos.js:6:10)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! csgo-reportbot@1.0.0 start: `node bot.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the csgo-reportbot@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\YOG\AppData\Roaming\npm-cache_logs\2019-03-11T17_44_42_471Z-debug.log
> 
> C:\Users\YOG\Downloads\node-csgo-reportbot-master\node-csgo-reportbot-master>

https://github.com/despa1r1337/reportbot
