### ISSUE TITLE
Cant logon with disabled Steam Guard

### ISSUE THREAD

**Issue by volovik** [Askwrite/node-csgo-reportbot#9]
`SteamID64 which will be reported: 76561198289301988
Initializing ReportBot by askwrite...
Credits: Trololo - Idea

/home/administrator/reportbot/node-csgo-reportbot/node_modules/steam/node_modules/steam-crypto/index.js:6
  var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);
                                 ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at Object.exports.generateSessionKey (/home/administrator/reportbot/node-csgo-reportbot/node_modules/steam/node_modules/steam-crypto/index.js:6:34)
    at SteamClient.handlers.(anonymous function) (/home/administrator/reportbot/node-csgo-reportbot/node_modules/steam/lib/steam_client.js:216:44)
    at SteamClient._netMsgReceived (/home/administrator/reportbot/node-csgo-reportbot/node_modules/steam/lib/steam_client.js:157:26)
    at Connection.EventEmitter.emit (events.js:95:17)
    at Connection._readPacket (/home/administrator/reportbot/node-csgo-reportbot/node_modules/steam/lib/connection.js:50:8)
    at Connection.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Connection.Readable.push (_stream_readable.js:127:10)
`

**Comment by tmmtta** [comment]
cd protos
node updater.js
cd ..
node bot
hf

**Comment by Askwrite** [comment]
Have you installed all the dependencies?

**Comment by volovik** [comment]
Maybe yes?

Today i am run update.js and check module, **npm ls** dont show me errors. look at that :

```
root@xubuntuserver:/home/administrator/reportbot/node-csgo-reportbot# npm ls
csgo-reportbot@1.0.0 /home/administrator/reportbot/node-csgo-reportbot
├── crypto@0.0.3
├── events@1.1.1
├── fs@0.0.2
├── https@1.0.0
├── long@3.1.0
├─┬ protobufjs@5.0.1
│ ├─┬ ascli@1.0.0
│ │ ├── colour@0.7.1
│ │ └── optjs@3.2.2
│ ├── bytebuffer@5.0.1
│ ├─┬ glob@5.0.15
│ │ ├─┬ inflight@1.0.5
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@3.0.2
│ │ │ └─┬ brace-expansion@1.1.5
│ │ │   ├── balanced-match@0.4.1
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.3.3
│ │ │ └── wrappy@1.0.2
│ │ └── path-is-absolute@1.0.0
│ └─┬ yargs@3.32.0
│   ├── camelcase@2.1.1
│   ├─┬ cliui@3.2.0
│   │ ├─┬ strip-ansi@3.0.1
│   │ │ └── ansi-regex@2.0.0
│   │ └── wrap-ansi@2.0.0
│   ├── decamelize@1.2.0
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ string-width@1.0.1
│   │ ├─┬ code-point-at@1.0.0
│   │ │ └── number-is-nan@1.0.0
│   │ ├─┬ is-fullwidth-code-point@1.0.0
│   │ │ └── number-is-nan@1.0.0
│   │ └─┬ strip-ansi@3.0.1
│   │   └── ansi-regex@2.0.0
│   ├── window-size@0.1.4
│   └── y18n@3.2.1
├─┬ protocol-buffers@3.1.6 extraneous
│ ├─┬ brfs@1.4.3
│ │ ├─┬ quote-stream@1.0.2
│ │ │ ├── buffer-equal@0.0.1
│ │ │ └── minimist@1.2.0
│ │ ├── resolve@1.1.7
│ │ ├─┬ static-module@1.3.1
│ │ │ ├─┬ concat-stream@1.4.10
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ ├─┬ readable-stream@1.1.14
│ │ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ │ ├── isarray@0.0.1
│ │ │ │ │ └── string_decoder@0.10.31
│ │ │ │ └── typedarray@0.0.6
│ │ │ ├─┬ duplexer2@0.0.2
│ │ │ │ └─┬ readable-stream@1.1.14
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   ├── inherits@2.0.1
│ │ │ │   ├── isarray@0.0.1
│ │ │ │   └── string_decoder@0.10.31
│ │ │ ├─┬ escodegen@1.3.3
│ │ │ │ ├── esprima@1.1.1
│ │ │ │ ├── estraverse@1.5.1
│ │ │ │ ├── esutils@1.0.0
│ │ │ │ └─┬ source-map@0.1.43
│ │ │ │   └── amdefine@1.0.0
│ │ │ ├─┬ falafel@1.2.0
│ │ │ │ ├── acorn@1.2.2
│ │ │ │ ├── foreach@2.0.5
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ └── object-keys@1.0.10
│ │ │ ├─┬ has@1.0.1
│ │ │ │ └── function-bind@1.1.0
│ │ │ ├── object-inspect@0.4.0
│ │ │ ├─┬ quote-stream@0.0.0
│ │ │ │ └── minimist@0.0.8
│ │ │ ├─┬ readable-stream@1.0.34
│ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ └── string_decoder@0.10.31
│ │ │ ├── shallow-copy@0.0.1
│ │ │ ├─┬ static-eval@0.2.4
│ │ │ │ └─┬ escodegen@0.0.28
│ │ │ │   ├── esprima@1.0.4
│ │ │ │   ├── estraverse@1.3.2
│ │ │ │   └── source-map@0.5.6
│ │ │ └─┬ through2@0.4.2
│ │ │   └─┬ xtend@2.1.2
│ │ │     └── object-keys@0.4.0
│ │ └─┬ through2@2.0.1
│ │   ├─┬ readable-stream@2.0.6
│ │   │ ├── core-util-is@1.0.2
│ │   │ ├── inherits@2.0.1
│ │   │ ├── isarray@1.0.0
│ │   │ ├── process-nextick-args@1.0.7
│ │   │ ├── string_decoder@0.10.31
│ │   │ └── util-deprecate@1.0.2
│ │   └── xtend@4.0.1
│ ├── generate-function@2.0.0
│ ├─┬ generate-object-property@1.2.0
│ │ └── is-property@1.0.2
│ ├── protocol-buffers-schema@2.2.0
│ ├─┬ signed-varint@2.0.0
│ │ └── varint@3.0.1
│ └── varint@4.0.1
├── q@1.4.1
├── readline-sync@1.4.4
├─┬ steam@1.4.0
│ ├── adm-zip@0.4.7
│ ├── buffer-crc32@0.2.5
│ ├─┬ bytebuffer@5.0.1
│ │ └── long@3.1.0
│ ├── steam-crypto@0.0.1
│ └─┬ steam-resources@1.0.0 (git+https://github.com/seishun/node-steam-resources.git#1403939a12ba467a4b82c8ccbc279bbcdad43588)
│   ├─┬ bytebuffer@5.0.0
│   │ └── long@3.0.1
│   └─┬ protobufjs@4.1.2
│     ├─┬ ascli@1.0.0
│     │ ├── colour@0.7.1
│     │ └── optjs@3.2.1-boom
│     ├─┬ bytebuffer@4.1.0
│     │ ├── bufferview@1.0.1
│     │ └── long@2.4.0
│     ├─┬ glob@5.0.15
│     │ ├─┬ inflight@1.0.4
│     │ │ └── wrappy@1.0.1
│     │ ├── inherits@2.0.1
│     │ ├─┬ minimatch@3.0.0
│     │ │ └─┬ brace-expansion@1.1.1
│     │ │   ├── balanced-match@0.2.1
│     │ │   └── concat-map@0.0.1
│     │ ├─┬ once@1.3.2
│     │ │ └── wrappy@1.0.1
│     │ └── path-is-absolute@1.0.0
│     └─┬ yargs@3.29.0
│       ├── camelcase@1.2.1
│       ├─┬ cliui@3.0.3
│       │ ├─┬ string-width@1.0.1
│       │ │ ├─┬ code-point-at@1.0.0
│       │ │ │ └── number-is-nan@1.0.0
│       │ │ └─┬ is-fullwidth-code-point@1.0.0
│       │ │   └── number-is-nan@1.0.0
│       │ ├─┬ strip-ansi@3.0.0
│       │ │ └── ansi-regex@2.0.0
│       │ └── wrap-ansi@1.0.0
│       ├── decamelize@1.1.1
│       ├─┬ os-locale@1.4.0
│       │ └─┬ lcid@1.0.0
│       │   └── invert-kv@1.0.0
│       ├── window-size@0.1.2
│       └── y18n@3.2.0
└─┬ steamid@1.1.0
  └── cuint@0.2.1

npm ERR! extraneous: protocol-buffers@3.1.6 /home/administrator/reportbot/node-csgo-reportbot/node_modules/protocol-buffers
npm ERR! not ok code 0


```


Today errors look like:

```
/home/administrator/reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:4688
                            throw Error("failed to import '"+importFilename+"'
                                  ^
Error: failed to import '/home/administrator/reportbot/node-csgo-reportbot/protos/engine_gcmessages.proto' in '/home/administrator/reportbot/node-csgo-reportbot/protos/cstrike15_gcmessages.proto': file not found
    at Error (<anonymous>)
    at ProtoBuf.Builder.BuilderPrototype.import (/home/administrator/reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:4688:35)
    at Object.ProtoBuf.loadJson (/home/administrator/reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:5183:26)
    at Object.ProtoBuf.loadProto (/home/administrator/reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:5086:25)
    at Object.ProtoBuf.loadProtoFile (/home/administrator/reportbot/node-csgo-reportbot/node_modules/protobufjs/dist/protobuf.js:5132:52)
    at Object.<anonymous> (/home/administrator/reportbot/node-csgo-reportbot/protos/protos.js:7:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

```

**Comment by volovik** [comment]
npm install crypto events fs https long protobufjs readline-sync

**Comment by Askwrite** [comment]
That's already in my packages.json file.
Maybe you forgot to run "npm install".
